spring:
    datasource:
        hikari:
            maximum-pool-size: 4
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:postgresql://localhost:9091/ProjectA
        username: postgres
        password: kk1598!!
        
    devtools:
        livereload:
            enabled: true

    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    jpa:
        hibernate.ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                show_sql: true
                format_sql: true
                generate_statistics: false
    servlet:
        multipart:
            maxFileSize: 50MB
            maxRequestSize: 50MB

mybatis:
    type-aliases-package: com.sis.template.mybatis.config
    mapper-locations: classpath:mapper/**/*.xml
#   config-location: classpath:mybatis-config.xml

# GeoServer:
#     WMS: http://localhost:9002/sde/wms
#     WFS: http://localhost:9002/sde/wfs

# jngis:
#     app:
#         jwtSecret: jwtGrokonezSecretKey
#         jwtExpiration: 86400
